[package]
name = "poison_girl_macro_def_features"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
poison_girl_macro_impl_features = { workspace = true }
poison_girl_proc_macro_helper = { workspace = true }
proc-macro2 = { workspace = true }
syn = { workspace = true }

[lints]
workspace = true
