[workspace]
default-members = ["crates/kernel", "crates/loader"]
members = [
  "crates/kernel",
  "crates/loader",
  "crates/no_std",
  "crates/error/*",
  "crates/dev/*",
  "crates/macro/helper",
  "crates/macro/macro",
  "crates/macro/*/def",
  "crates/macro/*/impl",
  "crates/macro/wrapper/*",
]
resolver = "2"

[workspace.dependencies]
aquamarine = "*"
clap = { version = "*", features = ["derive"] }
clap_derive = { version = "*" }
colored = "*"
html5ever = "*"
itertools = "*"
markup5ever_rcdom = "*"
ovmf-prebuilt = "*"
poison_girl_dev_cargo = { path = "./crates/dev/cargo/" }
poison_girl_dev_cli = { path = "./crates/dev/cli/" }
poison_girl_dev_error = { path = "./crates/error/dev/" }
poison_girl_dev_fs = { path = "./crates/dev/fs/" }
poison_girl_dev_orchestrate = { path = "./crates/dev/orchestrate/" }
poison_girl_dev_util = { path = "./crates/dev/util/" }
poison_girl_kernel = { path = "./crates/kernel/" }
poison_girl_macro = { path = "./crates/macro/macro/" }
poison_girl_macro_def_features = { path = "./crates/macro/features/def/" }
poison_girl_macro_def_font = { path = "./crates/macro/font/def/" }
poison_girl_macro_def_from_path_buf = { path = "./crates/macro/from_path_buf/def/" }
poison_girl_macro_def_impl_int = { path = "./crates/macro/impl_int/def/" }
poison_girl_macro_def_status = { path = "./crates/macro/status/def/" }
poison_girl_macro_def_test_elf_header_parse = { path = "./crates/macro/test_elf_header_parse/def/" }
poison_girl_macro_def_test_program_headers_parse = { path = "./crates/macro/test_program_headers_parse/def/" }
poison_girl_macro_def_wrapper = { path = "./crates/macro/wrapper/macro/" }
poison_girl_macro_impl_features = { path = "./crates/macro/features/impl/" }
poison_girl_macro_impl_font = { path = "./crates/macro/font/impl/" }
poison_girl_macro_impl_from_path_buf = { path = "./crates/macro/from_path_buf/impl/" }
poison_girl_macro_impl_impl_int = { path = "./crates/macro/impl_int/impl/" }
poison_girl_macro_impl_status = { path = "./crates/macro/status/impl/" }
poison_girl_macro_impl_test_elf_header_parse = { path = "./crates/macro/test_elf_header_parse/impl/" }
poison_girl_macro_impl_test_program_headers_parse = { path = "./crates/macro/test_program_headers_parse/impl/" }
poison_girl_macro_impl_wrapper = { path = "./crates/macro/wrapper/impl/" }
poison_girl_no_std = { path = "./crates/no_std/" }
poison_girl_no_std_error = { path = "./crates/error/no_std/" }
poison_girl_proc_macro_helper = { path = "./crates/macro/helper/" }
poison_girl_this_is_b_wrapper_dev = { path = "./crates/error/this_is_b_wrapper_dev/" }
poison_girl_this_is_b_wrapper_no_std = { path = "./crates/error/this_is_b_wrapper_no_std/" }
poison_girl_dev_test = { path = "./crates/dev/test/" }
proc-macro2 = "*"
quickcheck = "*"
quote = "*"
string_cache = "*"
strum = "*"
strum_macros = "*"
syn = { version = "*", features = ["full", "extra-traits"] }
tempfile = "*"
toml = { version = "*", features = ["parse"] }
ureq = { version = "*", features = ["cookies"] }
hadris-fat = { version = "*", features = ["sync", "write"] }

[workspace.lints.clippy]
tabs_in_doc_comments = "allow"
mut_from_ref = "allow"
# panicing APIs
unwrap_used = "forbid"
expect_used = "forbid"
panic = "forbid"
todo = "deny"
unimplemented = "forbid"
unreachable = "deny"

# [profile.dev.package.xtask]
# opt-level = 3

[package]
name = "poison_girl"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = { workspace = true }
hadris-fat = { workspace = true }
poison_girl_dev_cargo = { workspace = true }
poison_girl_dev_error = { workspace = true }
poison_girl_dev_fs = { workspace = true }
poison_girl_dev_orchestrate = { workspace = true }
poison_girl_dev_cli = { workspace = true }

[lints]
workspace = true
