[workspace]
members = ["crates/kernel", "crates/loader"]
resolver = "2"

[workspace.dependencies]
aquamarine = "*"
clap = { version = "*", features = ["derive"] }
clap_derive = { version = "*" }
colored = "*"
html5ever = "0.36"
itertools = "*"
markup5ever_rcdom = "*"
ovmf-prebuilt = "*"
poison_girl_dev_error = { path = "./crates/error/dev/" }
poison_girl_dev_fs = { path = "./crates/dev/fs/" }
poison_girl_dev_orchestrate = { path = "./crates/dev/orchestrate/" }
poison_girl_kernel = { path = "./crates/kernel/" }
poison_girl_macro = { path = "./crates/macro/macro/" }
poison_girl_no_std = { path = "./crates/no_std/" }
poison_girl_no_std_error = { path = "./crates/error/no_std/" }
proc-macro2 = "*"
quickcheck = "*"
quote = "*"
string_cache = "*"
strum = "*"
strum_macros = "*"
syn = { version = "*", features = ["full", "extra-traits"] }
tempfile = "*"
this_is_b = "*"
toml = { version = "*", features = ["parse"] }
ureq = { version = "*", features = ["cookies"] }

[workspace.lints.clippy]
tabs_in_doc_comments = "allow"
mut_from_ref = "allow"

# [profile.dev.package.xtask]
# opt-level = 3

[package]
name = "poison_girl"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = { workspace = true }
poison_girl_dev_error = { workspace = true }
poison_girl_dev_fs = { workspace = true }
poison_girl_dev_orchestrate = { workspace = true }
