[package]
name = "poison_girl_proc_macro_def"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
colored = { workspace = true }
poison_girl_dev_error = { workspace = true }
poison_girl_proc_macro_helper = { path = "../helper/" }
poison_girl_proc_macro_impl = { path = "../impl/" }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
