[package]
name = "shion_kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
kernel_pmacro_def = { path = "../macro_def" }
shion_error = { path = "../../deps/error" }

[features]
rgb = []
bgr = []
bitmask = []
bltonly = []
default = ["bltonly"]

[lints.clippy]
tabs_in_doc_comments = "allow"
assign_op_pattern = "allow"
mut_from_ref = "allow"
