[package]
name = "poison_girl_macro_def_wrapper"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
poison_girl_macro_impl_wrapper = { workspace = true }
poison_girl_proc_macro_helper = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
poison_girl_macro_error = { workspace = true }

[lints]
workspace = true
