[package]
name = "poison_girl_loader"
version = "0.1.0"
edition = "2024"

[dependencies]
poison_girl_macro = { workspace = true }
poison_girl_no_std = { workspace = true }
poison_girl_no_std_error = { workspace = true }

[lints]
workspace = true

[features]
default = ["bltonly"]
# Graphics pixel format support
rgb = []
bgr = []
bitmask = []
# Block transfer only mode (default)
bltonly = []
