[package]
name = "poison_girl_loader"
version = "0.1.0"
edition = "2024"

[dependencies]
poison_girl_macro = { workspace = true }
poison_girl_macro_def_status = { workspace = true }
poison_girl_macro_def_test_elf_header_parse = { workspace = true }
poison_girl_macro_def_test_program_headers_parse = { workspace = true }
poison_girl_no_std = { workspace = true }
poison_girl_no_std_error = { workspace = true }

[dev-dependencies]
poison_girl_dev_test = { workspace = true }

[lints]
workspace = true

[features]
default = ["bltonly"]
# Graphics pixel format support
rgb = []
bgr = []
bitmask = []
# Block transfer only mode (default)
bltonly = []
