[package]
name = "kernel_pmacro_def"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "*"
kernel_pmacro_impl = { path = "../macro_impl" }
proc-macro2 = "*"
quote = "*"
shion_pmacro_helper = { path = "../../deps/pmacro_helper" }
syn = { version = "*", features = ["full", "extra-traits"] }
