[package]
name = "oso_proc_macro"
version = "0.1.0"
authors = ["sugiura hiromiti"]
categories = ["development-tools::procedural-macro-helpers", "os"]
documentation = "https://docs.rs/oso_proc_macro"
edition = "2024"
keywords = ["os", "kernel", "procedural-macros", "uefi", "elf"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/oso-project/oso"
description = "Procedural macros for the OSO operating system project"

[lib]
proc-macro = true

[dependencies]
anyhow = "*"
colored = "*"
oso_proc_macro_logic = { path = "../oso_proc_macro_logic" }
proc-macro2 = "*"
quote = "*"
syn = { version = "*", features = ["full", "extra-traits"] }
