[package]
name = "poison_girl_macro_def_test_program_headers_parse"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
poison_girl_macro_impl_test_program_headers_parse = { workspace = true }
poison_girl_proc_macro_helper = { workspace = true }
proc-macro2 = { workspace = true }
syn = { workspace = true, features = ["parsing"] }
poison_girl_macro_error = { workspace = true }

[lints]
workspace = true
