[package]
name = "poison_girl_dev_cargo"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { workspace = true }
ovmf-prebuilt = { workspace = true }
poison_girl_dev_error = { workspace = true }
poison_girl_dev_fs = { workspace = true }
poison_girl_macro = { workspace = true }
poison_girl_macro_def_features = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }

[lints]
workspace = true
